#!/bin/bash
#
# interactive-install-mods — Download and install mods from server
#

PROJECT_DIR="$(cd "$(dirname "$0")/../.." && pwd)"
source "$PROJECT_DIR/lib/common"
source "$PROJECT_DIR/lib/config"

bash "$PROJECT_DIR/layer1/player/install-mods"