#!/bin/bash
#
# interactive-edit-client-cfg — Edit tes3mp-client-default.cfg
#

PROJECT_DIR="$(cd "$(dirname "$0")/../.." && pwd)"
source "$PROJECT_DIR/lib/common"
source "$PROJECT_DIR/lib/config"

bash "$PROJECT_DIR/layer1/player/edit-client-cfg"