#!/bin/bash
#
# interactive-run-openmw-cs — Launch OpenMW-CS via Proton
#

PROJECT_DIR="$(cd "$(dirname "$0")/../.." && pwd)"
source "$PROJECT_DIR/lib/common"
source "$PROJECT_DIR/lib/config"

bash "$PROJECT_DIR/layer1/player/run-openmw-cs"