#!/bin/bash
#
# config.sh — tes3mp-easy configuration (~/.tes3mp-easy.conf)
#
# Provides:
#   - load_config()      — source the config file
#   - save_config()      — write config file
#   - edit_config()      — open config in nano
#   - first_run_wizard() — interactive setup on first launch
#   - show_config()      — display current configuration
#

# ────────────────────────────────────────────────────────────
# Guard against sourcing twice + ensure common.sh is loaded
# ────────────────────────────────────────────────────────────
if [[ -z "${LIB_DIR:-}" ]]; then
    echo "ERROR: common.sh must be sourced before config.sh" >&2
    exit 1
fi

CONFIG_FILE="${CONFIG_FILE:-$HOME/.tes3mp-easy.conf}"

# ────────────────────────────────────────────────────────────
# Default configuration values
# ────────────────────────────────────────────────────────────
CONFIG_DEFAULTS_ADMIN=(
    "ROLE=admin"
    "SSH_HOST="
    "PLUGINS_DIR="
    "SERVER_SCRIPTS_DIR="
)

CONFIG_DEFAULTS_PLAYER=(
    "ROLE=player"
    "SERVER_URL="
    "DATA_FILES="
    "OPENMW_CFG="
    "CLIENT_DEFAULT="
)

# ────────────────────────────────────────────────────────────
# load_config — source ~/.tes3mp-easy.conf if it exists
# Returns 0 if loaded, 1 if missing
# ────────────────────────────────────────────────────────────
load_config() {
    if [[ -f "$CONFIG_FILE" ]]; then
        source "$CONFIG_FILE"
        return 0
    fi
    return 1
}

# ────────────────────────────────────────────────────────────
# save_config — write current variables to config file
# Variables must be exported or passed as arguments
# Usage: save_config VAR1 VAR2 VAR3
# ────────────────────────────────────────────────────────────
save_config() {
    local vars=("$@")
    local tmp_file
    tmp_file=$(mktemp)

    cat > "$tmp_file" << 'EOF'
# TES3MP Easy configuration
# Generated by tes3mp-easy
# Edit with: ./tes3mp-easy config
EOF
    echo "" >> "$tmp_file"

    for var in "${vars[@]}"; do
        local value="${!var:-}"
        echo "${var}=${value}" >> "$tmp_file"
    done

    # Preserve existing comments if file exists
    if [[ -f "$CONFIG_FILE" ]]; then
        # Keep any non-variable lines (comments)
        while IFS= read -r line; do
            if [[ ! "$line" =~ ^[A-Z_]+= && -n "$line" ]]; then
                echo "$line" >> "$tmp_file"
            fi
        done < "$CONFIG_FILE"
    fi

    # Remove duplicate blank lines
    awk '!NF { if (++n <= 1) print; next } { n=0; print }' "$tmp_file" > "$CONFIG_FILE"
    rm -f "$tmp_file"
    chmod 600 "$CONFIG_FILE"
    ok "Configuration saved to $CONFIG_FILE"
}

# ────────────────────────────────────────────────────────────
# edit_config — open config in nano
# ────────────────────────────────────────────────────────────
edit_config() {
    check_deps nano
    if [[ ! -f "$CONFIG_FILE" ]]; then
        err "Config file not found: $CONFIG_FILE"
        err "Run './tes3mp-easy' without arguments to start the setup wizard."
        return 1
    fi
    nano "$CONFIG_FILE"
    ok "Config file saved."
}

# ────────────────────────────────────────────────────────────
# show_config — display current configuration
# ────────────────────────────────────────────────────────────
show_config() {
    if [[ ! -f "$CONFIG_FILE" ]]; then
        warn "Config file not found: $CONFIG_FILE"
        return 1
    fi

    echo ""
    echo "═══════════════════════════════════════════════"
    echo "  TES3MP Easy Configuration"
    echo "═══════════════════════════════════════════════"
    echo ""
    while IFS= read -r line; do
        case "$line" in
            ROLE=*)       echo "  Role:          ${line#*=}" ;;
            SSH_HOST=*)   echo "  SSH Host:      ${line#*=:-}" ;;
            PLUGINS_DIR=*) echo "  Plugins Dir:   ${line#*=:-}" ;;
            SERVER_*)     echo "  Server Scripts:${line#*=:-}" ;;
            SERVER_URL=*) echo "  Server URL:    ${line#*=:-}" ;;
            DATA_FILES=*) echo "  Data Files:    ${line#*=:-}" ;;
            OPENMW_CFG=*) echo "  OpenMW Config: ${line#*=:-}" ;;
            CLIENT_*)     echo "  Client Config: ${line#*=:-}" ;;
        esac
    done < "$CONFIG_FILE"
    echo ""
}

# ────────────────────────────────────────────────────────────
# first_run_wizard — interactive setup on first launch
# ────────────────────────────────────────────────────────────
first_run_wizard() {
    echo ""
    echo "╔══════════════════════════════════════════════════╗"
    echo "║     Welcome to TES3MP Easy!                     ║"
    echo "║     This is your first run — let's set up.      ║"
    echo "╚══════════════════════════════════════════════════╝"
    echo ""

    # ─── Role selection ───
    echo "Are you a server admin or a player?"
    echo "  1) Admin  — I manage a TES3MP server"
    echo "  2) Player — I want to play on a server"
    echo ""

    local role_choice
    while true; do
        read -r -p "Select [1/2]: " role_choice
        case "$role_choice" in
            1) ROLE="admin"; break ;;
            2) ROLE="player"; break ;;
            *) echo "Please enter 1 or 2." ;;
        esac
    done

    echo ""

    if [[ "$ROLE" == "admin" ]]; then
        wizard_admin
    else
        wizard_player
    fi

    # Save configuration
    if [[ "$ROLE" == "admin" ]]; then
        save_config ROLE SSH_HOST PLUGINS_DIR SERVER_SCRIPTS_DIR
    else
        save_config ROLE SERVER_URL DATA_FILES OPENMW_CFG CLIENT_DEFAULT
    fi

    ok "Setup complete!"
    echo ""
    echo "You can edit these settings later with:  ./tes3mp-easy config"
    echo ""
    press_enter
}

# ────────────────────────────────────────────────────────────
# wizard_admin — admin-specific configuration questions
# ────────────────────────────────────────────────────────────
wizard_admin() {
    # SSH_HOST
    echo "--- SSH Host ---"
    echo "Enter the SSH host for your VPS (as configured in ~/.ssh/config)."
    echo "Example: my-server"
    echo ""
    read -r -p "SSH host: " SSH_HOST
    SSH_HOST="${SSH_HOST:-}"
    if [[ -z "$SSH_HOST" ]]; then
        warn "SSH host is empty. You can set it later in the config."
    fi

    echo ""

    # PLUGINS_DIR
    local detected_mw
    detected_mw=$(detect_morrowind_path 2>/dev/null || echo "")
    local plugins_default=""
    if [[ -n "$detected_mw" ]]; then
        plugins_default="$detected_mw/Data Files"
    fi

    echo "--- Plugins Directory ---"
    echo "Path to your Morrowind Data Files (where .esp/.esm files are stored)."
    [[ -n "$plugins_default" ]] && echo "Detected: $plugins_default"
    echo ""
    read -r -p "Plugins dir${plugins_default:+ [$plugins_default]}: " input
    PLUGINS_DIR="${input:-$plugins_default}"
    PLUGINS_DIR="${PLUGINS_DIR:-}"

    echo ""

    # SERVER_SCRIPTS_DIR
    local scripts_default="$PWD/server_setup/mods/scripts"
    if [[ ! -d "$scripts_default" ]]; then
        scripts_default="$PWD/mods/scripts"
    fi
    if [[ ! -d "$scripts_default" ]]; then
        scripts_default=""
    fi

    echo "--- Server Scripts Directory ---"
    echo "Path to your Lua server scripts directory."
    [[ -n "$scripts_default" ]] && echo "Suggested: $scripts_default"
    echo ""
    read -r -p "Server scripts dir${scripts_default:+ [$scripts_default]}: " input
    SERVER_SCRIPTS_DIR="${input:-$scripts_default}"
    SERVER_SCRIPTS_DIR="${SERVER_SCRIPTS_DIR:-}"
}

# ────────────────────────────────────────────────────────────
# wizard_player — player-specific configuration questions
# ────────────────────────────────────────────────────────────
wizard_player() {
    # SERVER_URL
    echo "--- Server URL ---"
    echo "Enter the URL of the TES3MP server (with port if non-standard)."
    echo "Example: http://192.168.1.100:8085"
    echo ""
    read -r -p "Server URL: " SERVER_URL
    SERVER_URL="${SERVER_URL:-}"

    echo ""

    # DATA_FILES
    local detected_mw
    detected_mw=$(detect_morrowind_path 2>/dev/null || echo "")
    local data_default=""
    if [[ -n "$detected_mw" ]]; then
        data_default="$detected_mw/Data Files"
    fi

    echo "--- Data Files Directory ---"
    echo "Path to your Morrowind Data Files (where .esp/.esm files are stored)."
    [[ -n "$data_default" ]] && echo "Detected: $data_default"
    echo ""
    read -r -p "Data Files dir${data_default:+ [$data_default]}: " input
    DATA_FILES="${input:-$data_default}"
    DATA_FILES="${DATA_FILES:-}"

    echo ""

    # OPENMW_CFG
    local openmw_default=""
    if is_os "linux"; then
        local steam_path
        steam_path=$(detect_steam_path 2>/dev/null || echo "")
        if [[ -n "$steam_path" ]]; then
            local compat_wizard
            compat_wizard=$(find "$steam_path/steamapps/compatdata" -maxdepth 2 -name "*.reg" -exec grep -l "openmw-wizard" {} \; 2>/dev/null | head -1)
            if [[ -n "$compat_wizard" ]]; then
                local compat_id
                compat_id=$(echo "$compat_wizard" | grep -oP 'compatdata/\K[0-9]+')
                if [[ -n "$compat_id" ]]; then
                    openmw_default="$HOME/.steam/steam/steamapps/compatdata/$compat_id/pfx/drive_c/users/steamuser/Documents/My Games/OpenMW/openmw.cfg"
                fi
            fi
        fi
    fi

    echo "--- OpenMW Config ---"
    echo "Path to your openmw.cfg file."
    [[ -n "$openmw_default" ]] && echo "Detected: $openmw_default"
    echo ""
    read -r -p "openmw.cfg path${openmw_default:+ [$openmw_default]}: " input
    OPENMW_CFG="${input:-$openmw_default}"
    OPENMW_CFG="${OPENMW_CFG:-}"

    echo ""

    # CLIENT_DEFAULT
    local client_default=""
    if is_os "linux"; then
        local steam_path
        steam_path=$(detect_steam_path 2>/dev/null || echo "")
        if [[ -n "$steam_path" ]]; then
            local compat_tes3mp
            compat_tes3mp=$(find "$steam_path/steamapps/compatdata" -maxdepth 2 -name "*.reg" -exec grep -l "tes3mp" {} \; 2>/dev/null | head -1)
            if [[ -n "$compat_tes3mp" ]]; then
                local compat_id
                compat_id=$(echo "$compat_tes3mp" | grep -oP 'compatdata/\K[0-9]+')
                if [[ -n "$compat_id" ]]; then
                    local tes3mp_dir
                    tes3mp_dir=$(find "$steam_path/steamapps/compatdata/$compat_id/pfx/drive_c" -name "tes3mp.exe" 2>/dev/null | head -1)
                    if [[ -n "$tes3mp_dir" ]]; then
                        client_default="$(dirname "$tes3mp_dir")/tes3mp-client-default.cfg"
                    fi
                fi
            fi
        fi
    fi

    echo "--- TES3MP Client Config ---"
    echo "Path to your tes3mp-client-default.cfg file."
    [[ -n "$client_default" ]] && echo "Detected: $client_default"
    echo ""
    read -r -p "Client config path${client_default:+ [$client_default]}: " input
    CLIENT_DEFAULT="${input:-$client_default}"
    CLIENT_DEFAULT="${CLIENT_DEFAULT:-}"
}

# ────────────────────────────────────────────────────────────
# Check OS compatibility
# ────────────────────────────────────────────────────────────
if is_os "windows"; then
    warn "Windows detected. Some features require Git Bash or WSL."
    warn "The menu uses 'select' which works in Git Bash."
fi