#!/bin/bash
#
# config.sh — tes3mp-easy configuration
#
# Two separate config files:
#   ~/.tes3mp-easy-admin.conf   — for admins (SSH_HOST, PLUGINS_DIR, ...)
#   ~/.tes3mp-easy-player.conf  — for players (SERVER_URL, DATA_FILES, ...)
#
# Provides:
#   - load_config(file)  — source the config file
#   - save_config(file)  — write config file
#   - edit_config(file)  — open config in nano
#   - wizard_admin()     — interactive setup for admins
#   - wizard_player()    — interactive setup for players
#   - show_config(file)  — display current configuration
#

if [[ -z "${LIB_DIR:-}" ]]; then
    echo "ERROR: common.sh must be sourced before config.sh" >&2
    exit 1
fi

ADMIN_CONFIG="${HOME}/.tes3mp-easy-admin.conf"
PLAYER_CONFIG="${HOME}/.tes3mp-easy-player.conf"

# ────────────────────────────────────────────────────────────
# load_config — source config file
# Usage: load_config [path]
# If no path given, tries admin, then player
# Returns 0 if loaded, 1 if missing
# ────────────────────────────────────────────────────────────
load_config() {
    local file="${1:-}"

    if [[ -z "$file" ]]; then
        # Auto-detect: try admin first, then player
        if [[ -f "$ADMIN_CONFIG" ]]; then
            file="$ADMIN_CONFIG"
        elif [[ -f "$PLAYER_CONFIG" ]]; then
            file="$PLAYER_CONFIG"
        else
            return 1
        fi
    fi

    if [[ -f "$file" ]]; then
        source "$file"
        return 0
    fi
    return 1
}

# ────────────────────────────────────────────────────────────
# save_config — write config file
# Usage: save_config <file> VAR1 VAR2 VAR3
# ────────────────────────────────────────────────────────────
save_config() {
    local file="$1"
    shift
    local vars=("$@")
    local tmp_file
    tmp_file=$(mktemp)

    cat > "$tmp_file" << 'EOF'
# TES3MP Easy configuration
# Generated by tes3mp-easy
EOF
    echo "" >> "$tmp_file"

    for var in "${vars[@]}"; do
        local value="${!var:-}"
        echo "${var}=${value}" >> "$tmp_file"
    done

    awk '!NF { if (++n <= 1) print; next } { n=0; print }' "$tmp_file" > "$file"
    rm -f "$tmp_file"
    chmod 600 "$file"
    ok "Configuration saved to $file"
}

# ────────────────────────────────────────────────────────────
# edit_config — open config in nano
# Usage: edit_config [file]
# ────────────────────────────────────────────────────────────
edit_config() {
    check_deps nano

    # Determine which config to edit based on ROLE or auto-detect
    local file="${1:-}"
    if [[ -z "$file" ]]; then
        if [[ -f "$ADMIN_CONFIG" ]]; then
            file="$ADMIN_CONFIG"
        elif [[ -f "$PLAYER_CONFIG" ]]; then
            file="$PLAYER_CONFIG"
        else
            err "No config file found. Run install script first."
            return 1
        fi
    fi

    if [[ ! -f "$file" ]]; then
        err "Config file not found: $file"
        return 1
    fi
    nano "$file"
    ok "Config file saved."
}

# ────────────────────────────────────────────────────────────
# show_config — display current configuration
# Usage: show_config [file]
# ────────────────────────────────────────────────────────────
show_config() {
    local file="${1:-}"
    if [[ -z "$file" ]]; then
        file="$ADMIN_CONFIG"
        [[ -f "$file" ]] || file="$PLAYER_CONFIG"
    fi

    if [[ ! -f "$file" ]]; then
        warn "Config file not found."
        return 1
    fi

    echo ""
    echo "═══════════════════════════════════════════════"
    echo "  TES3MP Easy Configuration"
    echo "═══════════════════════════════════════════════"
    echo ""
    while IFS= read -r line; do
        case "$line" in
            ROLE=*)       echo "  Role:          ${line#*=}" ;;
            SSH_HOST=*)   echo "  SSH Host:      ${line#*=}" ;;
            PLUGINS_DIR=*) echo "  Plugins Dir:   ${line#*=}" ;;
            SERVER_*)     echo "  Server Scripts:${line#*=}" ;;
            SERVER_URL=*) echo "  Server URL:    ${line#*=}" ;;
            DATA_FILES=*) echo "  Data Files:    ${line#*=}" ;;
            OPENMW_CFG=*) echo "  OpenMW Config: ${line#*=}" ;;
            CLIENT_*)     echo "  Client Config: ${line#*=}" ;;
            "#"*)         ;;  # skip comments
        esac
    done < "$file"
    echo ""
}

# ────────────────────────────────────────────────────────────
# wizard_admin — interactive setup for admin (no role question)
# ────────────────────────────────────────────────────────────
wizard_admin() {
    local first_run="${1:-false}"

    if [[ "$first_run" == "true" ]]; then
        echo ""
        echo "╔══════════════════════════════════════════════════╗"
        echo "║     Welcome to TES3MP Easy!                     ║"
        echo "║     Admin profile — let's configure.            ║"
        echo "╚══════════════════════════════════════════════════╝"
        echo ""
    fi

    # SSH_HOST
    echo "--- SSH Host ---"
    echo "Enter the SSH host for your VPS (as configured in ~/.ssh/config)."
    echo "Example: my-server"
    echo ""
    read -r -p "SSH host: " SSH_HOST
    SSH_HOST="${SSH_HOST:-}"
    if [[ -z "$SSH_HOST" ]]; then
        warn "SSH host is empty. You can set it later in the config."
    fi
    echo ""

    # PLUGINS_DIR
    local detected_mw
    detected_mw=$(detect_morrowind_path 2>/dev/null || echo "")
    local plugins_default=""
    if [[ -n "$detected_mw" ]]; then
        plugins_default="$detected_mw/Data Files"
    fi

    echo "--- Plugins Directory ---"
    echo "Path to your Morrowind Data Files (where .esp/.esm files are stored)."
    [[ -n "$plugins_default" ]] && echo "Detected: $plugins_default"
    echo ""
    read -r -p "Plugins dir${plugins_default:+ [$plugins_default]}: " input
    PLUGINS_DIR="${input:-$plugins_default}"
    PLUGINS_DIR="${PLUGINS_DIR:-}"
    echo ""

    # SERVER_SCRIPTS_DIR
    local scripts_default=""
    local candidates=("$PWD/mods/scripts" "$PWD/server/mods/scripts")
    for d in "${candidates[@]}"; do
        if [[ -d "$d" ]]; then
            scripts_default="$d"
            break
        fi
    done

    echo "--- Server Scripts Directory ---"
    echo "Path to your Lua server scripts directory."
    [[ -n "$scripts_default" ]] && echo "Suggested: $scripts_default"
    echo ""
    read -r -p "Server scripts dir${scripts_default:+ [$scripts_default]}: " input
    SERVER_SCRIPTS_DIR="${input:-$scripts_default}"
    SERVER_SCRIPTS_DIR="${SERVER_SCRIPTS_DIR:-}"

    # Save
    save_config "$ADMIN_CONFIG" ROLE SSH_HOST PLUGINS_DIR SERVER_SCRIPTS_DIR
    ok "Admin configuration saved."
    echo ""
    echo "You can edit these settings later with:  nano $ADMIN_CONFIG"
    echo ""
}

# ────────────────────────────────────────────────────────────
# wizard_player — interactive setup for player (no role question)
# ────────────────────────────────────────────────────────────
wizard_player() {
    local first_run="${1:-false}"

    if [[ "$first_run" == "true" ]]; then
        echo ""
        echo "╔══════════════════════════════════════════════════╗"
        echo "║     Welcome to TES3MP Easy!                     ║"
        echo "║     Player profile — let's configure.           ║"
        echo "╚══════════════════════════════════════════════════╝"
        echo ""
    fi

    # SERVER_URL
    echo "--- Server URL ---"
    echo "Enter the URL of the TES3MP server (with port if non-standard)."
    echo "Example: http://192.168.1.100:8085"
    echo ""
    read -r -p "Server URL: " SERVER_URL
    SERVER_URL="${SERVER_URL:-}"
    echo ""

    # DATA_FILES
    local detected_mw
    detected_mw=$(detect_morrowind_path 2>/dev/null || echo "")
    local data_default=""
    if [[ -n "$detected_mw" ]]; then
        data_default="$detected_mw/Data Files"
    fi

    echo "--- Data Files Directory ---"
    echo "Path to your Morrowind Data Files (where .esp/.esm files are stored)."
    [[ -n "$data_default" ]] && echo "Detected: $data_default"
    echo ""
    read -r -p "Data Files dir${data_default:+ [$data_default]}: " input
    DATA_FILES="${input:-$data_default}"
    DATA_FILES="${DATA_FILES:-}"
    echo ""

    # OPENMW_CFG
    local openmw_default=""
    if is_os "linux"; then
        local steam_path
        steam_path=$(detect_steam_path 2>/dev/null || echo "")
        if [[ -n "$steam_path" ]]; then
            local compat_wizard
            compat_wizard=$(find "$steam_path/steamapps/compatdata" -maxdepth 2 -name "*.reg" -exec grep -l "openmw-wizard" {} \; 2>/dev/null | head -1)
            if [[ -n "$compat_wizard" ]]; then
                local compat_id
                compat_id=$(echo "$compat_wizard" | grep -oP 'compatdata/\K[0-9]+')
                if [[ -n "$compat_id" ]]; then
                    openmw_default="$HOME/.steam/steam/steamapps/compatdata/$compat_id/pfx/drive_c/users/steamuser/Documents/My Games/OpenMW/openmw.cfg"
                fi
            fi
        fi
    fi

    echo "--- OpenMW Config ---"
    echo "Path to your openmw.cfg file."
    [[ -n "$openmw_default" ]] && echo "Detected: $openmw_default"
    echo ""
    read -r -p "openmw.cfg path${openmw_default:+ [$openmw_default]}: " input
    OPENMW_CFG="${input:-$openmw_default}"
    OPENMW_CFG="${OPENMW_CFG:-}"
    echo ""

    # CLIENT_DEFAULT
    local client_default=""
    if is_os "linux"; then
        local steam_path
        steam_path=$(detect_steam_path 2>/dev/null || echo "")
        if [[ -n "$steam_path" ]]; then
            local compat_tes3mp
            compat_tes3mp=$(find "$steam_path/steamapps/compatdata" -maxdepth 2 -name "*.reg" -exec grep -l "tes3mp" {} \; 2>/dev/null | head -1)
            if [[ -n "$compat_tes3mp" ]]; then
                local compat_id
                compat_id=$(echo "$compat_tes3mp" | grep -oP 'compatdata/\K[0-9]+')
                if [[ -n "$compat_id" ]]; then
                    local tes3mp_dir
                    tes3mp_dir=$(find "$steam_path/steamapps/compatdata/$compat_id/pfx/drive_c" -name "tes3mp.exe" 2>/dev/null | head -1)
                    if [[ -n "$tes3mp_dir" ]]; then
                        client_default="$(dirname "$tes3mp_dir")/tes3mp-client-default.cfg"
                    fi
                fi
            fi
        fi
    fi

    echo "--- TES3MP Client Config ---"
    echo "Path to your tes3mp-client-default.cfg file."
    [[ -n "$client_default" ]] && echo "Detected: $client_default"
    echo ""
    read -r -p "Client config path${client_default:+ [$client_default]}: " input
    CLIENT_DEFAULT="${input:-$client_default}"
    CLIENT_DEFAULT="${CLIENT_DEFAULT:-}"

    # Save
    save_config "$PLAYER_CONFIG" ROLE SERVER_URL DATA_FILES OPENMW_CFG CLIENT_DEFAULT
    ok "Player configuration saved."
    echo ""
    echo "You can edit these settings later with:  nano $PLAYER_CONFIG"
    echo ""
}

# ────────────────────────────────────────────────────────────
# OS compatibility check
# ────────────────────────────────────────────────────────────
if is_os "windows"; then
    warn "Windows detected. Some features require Git Bash or WSL."
    warn "The menu uses 'select' which works in Git Bash."
fi