#!/bin/bash
#
# interactive-export-players — Package and upload player data to server
#

PROJECT_DIR="$(cd "$(dirname "$0")/../.." && pwd)"
source "$PROJECT_DIR/lib/common"
source "$PROJECT_DIR/lib/config"

bash "$PROJECT_DIR/layer1/admin/export-players"