#!/bin/bash
#
# interactive-server-start — Start TES3MP server on remote VPS
#

PROJECT_DIR="$(cd "$(dirname "$0")/../.." && pwd)"
source "$PROJECT_DIR/lib/common"
source "$PROJECT_DIR/lib/config"

bash "$PROJECT_DIR/layer1/admin/start-server"