#!/bin/bash
#
# interactive-generate-data — Generate requiredDataFiles.json for mods
#

PROJECT_DIR="$(cd "$(dirname "$0")/../.." && pwd)"
source "$PROJECT_DIR/lib/common"
source "$PROJECT_DIR/lib/config"

bash "$PROJECT_DIR/layer1/admin/generate-data"