limit_req_zone $binary_remote_addr zone=download:10m rate=10r/m;
limit_req_zone $binary_remote_addr zone=list:10m rate=30r/m;

server {
    listen 80;
    server_name _;

    # All /download/* requests go to export server
    location /download/ {
        limit_req zone=download burst=3 nodelay;
        proxy_pass http://export:5000/download/;
    }

    # List backups
    location /list-backups/ {
        limit_req zone=list burst=5 nodelay;
        proxy_pass http://export:5000/list-backups/;
    }

    location / {
        return 404;
    }
}
